### ISSUE TITLE
Act 11.Diseño de circuitos logicos en fisìco.

### ISSUE THREAD

**Issue by Alondra-oss** [SistemasTecTlaxiaco/compuertas-logicas-team-sael-1as#1]
[ACT11 Diseño de circuitos logicos.pdf](https://github.com/user-attachments/files/18065913/ACT11.Diseno.de.circuitos.logicos.pdf)

**Comment by Victor-noe12** [comment]
Portada:25/25
Procedimiento/Desarrollo:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
bien hecho y revisado..
